// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: service_b/service_b.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	shared "github.com/phev8/go_commons/pkg/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DataObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counter      int64                `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	CommonObject *shared.CommonObject `protobuf:"bytes,2,opt,name=common_object,json=commonObject,proto3" json:"common_object,omitempty"`
}

func (x *DataObject) Reset() {
	*x = DataObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_b_service_b_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataObject) ProtoMessage() {}

func (x *DataObject) ProtoReflect() protoreflect.Message {
	mi := &file_service_b_service_b_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataObject.ProtoReflect.Descriptor instead.
func (*DataObject) Descriptor() ([]byte, []int) {
	return file_service_b_service_b_proto_rawDescGZIP(), []int{0}
}

func (x *DataObject) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *DataObject) GetCommonObject() *shared.CommonObject {
	if x != nil {
		return x.CommonObject
	}
	return nil
}

var File_service_b_service_b_proto protoreflect.FileDescriptor

var file_service_b_service_b_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x1a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x39,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x43, 0x0a, 0x08, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x12, 0x37, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x68, 0x65,
	0x76, 0x38, 0x2f, 0x67, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x42, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_b_service_b_proto_rawDescOnce sync.Once
	file_service_b_service_b_proto_rawDescData = file_service_b_service_b_proto_rawDesc
)

func file_service_b_service_b_proto_rawDescGZIP() []byte {
	file_service_b_service_b_proto_rawDescOnce.Do(func() {
		file_service_b_service_b_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_b_service_b_proto_rawDescData)
	})
	return file_service_b_service_b_proto_rawDescData
}

var file_service_b_service_b_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_b_service_b_proto_goTypes = []interface{}{
	(*DataObject)(nil),           // 0: service_b.DataObject
	(*shared.CommonObject)(nil),  // 1: common.CommonObject
	(*shared.RequestObject)(nil), // 2: common.RequestObject
}
var file_service_b_service_b_proto_depIdxs = []int32{
	1, // 0: service_b.DataObject.common_object:type_name -> common.CommonObject
	2, // 1: service_b.ServiceB.getData:input_type -> common.RequestObject
	0, // 2: service_b.ServiceB.getData:output_type -> service_b.DataObject
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_b_service_b_proto_init() }
func file_service_b_service_b_proto_init() {
	if File_service_b_service_b_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_b_service_b_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_b_service_b_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_b_service_b_proto_goTypes,
		DependencyIndexes: file_service_b_service_b_proto_depIdxs,
		MessageInfos:      file_service_b_service_b_proto_msgTypes,
	}.Build()
	File_service_b_service_b_proto = out.File
	file_service_b_service_b_proto_rawDesc = nil
	file_service_b_service_b_proto_goTypes = nil
	file_service_b_service_b_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceBClient is the client API for ServiceB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceBClient interface {
	GetData(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*DataObject, error)
}

type serviceBClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceBClient(cc grpc.ClientConnInterface) ServiceBClient {
	return &serviceBClient{cc}
}

func (c *serviceBClient) GetData(ctx context.Context, in *shared.RequestObject, opts ...grpc.CallOption) (*DataObject, error) {
	out := new(DataObject)
	err := c.cc.Invoke(ctx, "/service_b.ServiceB/getData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceBServer is the server API for ServiceB service.
type ServiceBServer interface {
	GetData(context.Context, *shared.RequestObject) (*DataObject, error)
}

// UnimplementedServiceBServer can be embedded to have forward compatible implementations.
type UnimplementedServiceBServer struct {
}

func (*UnimplementedServiceBServer) GetData(context.Context, *shared.RequestObject) (*DataObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}

func RegisterServiceBServer(s *grpc.Server, srv ServiceBServer) {
	s.RegisterService(&_ServiceB_serviceDesc, srv)
}

func _ServiceB_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.RequestObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceBServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service_b.ServiceB/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceBServer).GetData(ctx, req.(*shared.RequestObject))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service_b.ServiceB",
	HandlerType: (*ServiceBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getData",
			Handler:    _ServiceB_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_b/service_b.proto",
}
